### ISSUE TITLE
Fails on start

### ISSUE THREAD

**Issue by on-three** [alseambusher/crontab-ui#114]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues. 

reports error:
```
Node version: 13.5.0
Crontab UI is running at http://127.0.0.1:8000
/home/on-three/.nvm/versions/node/v13.5.0/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:240
          throw new Error(
          ^

Error: Constraint error, got value 0 expected range 1-31
    at handleResult (/home/on-three/.nvm/versions/node/v13.5.0/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:240:17)
    at parseSequence (/home/on-three/.nvm/versions/node/v13.5.0/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:260:7)
    at Function._parseField (/home/on-three/.nvm/versions/node/v13.5.0/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:351:10)
    at parse (/home/on-three/.nvm/versions/node/v13.5.0/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:774:36)
    at Function.parse (/home/on-three/.nvm/versions/node/v13.5.0/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:837:10)
    at Function.parseExpression (/home/on-three/.nvm/versions/node/v13.5.0/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/parser.js:41:25)
    at /home/on-three/.nvm/versions/node/v13.5.0/lib/node_modules/crontab-ui/crontab.js:65:32
    at newArguments.<computed> (/home/on-three/.nvm/versions/node/v13.5.0/lib/node_modules/crontab-ui/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/home/on-three/.nvm/versions/node/v13.5.0/lib/node_modules/crontab-ui/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/home/on-three/.nvm/versions/node/v13.5.0/lib/node_modules/crontab-ui/node_modules/nedb/lib/cursor.js:126:19)```
```

I'm pretty sure this happens because I used `0` to represent Sunday when I created my last job. Supporting Sunday as either `0` or `7` seems pretty much standard cron so this issue coming up is major.

**Comment by on-three** [comment]
Okay to clarify. Trying to schedule every sunday @ 1:30PM (weekly). I was reading `day` box as `day of week` but its meaning sems to be `day of the month`. This needs to be clarified.
How then can I specify `day of week` ?

**Comment by alseambusher** [comment]
This has been fixed https://github.com/alseambusher/crontab-ui/commit/970e461621e6906ce7259b9dfcacbff90dae858b 

@on-three You can give day of the week in the last box https://en.wikipedia.org/wiki/Cron
