### ISSUE TITLE
Can not add jobs every X minutes/hours/... with /

### ISSUE THREAD

**Issue by Varovv** [alseambusher/crontab-ui#116]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues. 

I cannot add jobs like at 5 every 72 hours, the parser crash. I have tried with 5/72, but do not save to crontab, I have tried too with 5\/72 but crashes. How can I add these jobs? Please fix it.

Here is the error:

Error: Invalid characters, got value: 5\/72
    at Function._parseField (/usr/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:186:11)
    at parse (/usr/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:774:36)
    at Function.parse (/usr/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:837:10)
    at Function.parseExpression (/usr/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/parser.js:41:25)
    at /usr/lib/node_modules/crontab-ui/crontab.js:65:32
    at newArguments.(anonymous function) (/usr/lib/node_modules/crontab-ui/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/usr/lib/node_modules/crontab-ui/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/usr/lib/node_modules/crontab-ui/node_modules/nedb/lib/cursor.js:126:19)
    at /usr/lib/node_modules/crontab-ui/node_modules/nedb/lib/cursor.js:193:12
    at /usr/lib/node_modules/crontab-ui/node_modules/nedb/lib/datastore.js:329:14

**Comment by alseambusher** [comment]
You cannot set 5 times every 72 hours with cron like that. 5 times every 72 hours is once in 14.4 hours. You can use this expression:

https://crontab.guru/#24_*/14_*_*_*
