### ISSUE TITLE
Error: Constraint error, got value 58 expected range 0-23

### ISSUE THREAD

**Issue by erickAvSanti** [alseambusher/crontab-ui#117]
It doesn't me allowing to work with my cron tasks ...

Node version: 13.6.0
Crontab UI is running at http://0.0.0.0:9000
/home/xxxxxxxxx/.nvm/versions/node/v13.6.0/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:240
          throw new Error(
          ^

Error: Constraint error, got value 58 expected range 0-23
    at handleResult (/home/xxxxxxxxx/.nvm/versions/node/v13.6.0/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:240:17)
    at parseSequence (/home/xxxxxxxxx/.nvm/versions/node/v13.6.0/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:260:7)
    at Function._parseField (/home/xxxxxxxxx/.nvm/versions/node/v13.6.0/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:351:10)
    at parse (/home/xxxxxxxxx/.nvm/versions/node/v13.6.0/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:774:36)
    at Function.parse (/home/xxxxxxxxx/.nvm/versions/node/v13.6.0/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:837:10)
    at Function.parseExpression (/home/xxxxxxxxx/.nvm/versions/node/v13.6.0/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/parser.js:41:25)
    at /home/xxxxxxxxx/.nvm/versions/node/v13.6.0/lib/node_modules/crontab-ui/crontab.js:65:32
    at newArguments.<computed> (/home/xxxxxxxxx/.nvm/versions/node/v13.6.0/lib/node_modules/crontab-ui/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/home/xxxxxxxxx/.nvm/versions/node/v13.6.0/lib/node_modules/crontab-ui/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/home/xxxxxxxxx/.nvm/versions/node/v13.6.0/lib/node_modules/crontab-ui/node_modules/nedb/lib/cursor.js:126:19)

**Comment by alseambusher** [comment]
What is your cron expression?

**Comment by erickAvSanti** [comment]
Unfortunely I Type 58 on hour field input. So your application got save without any prevalidation, then in refreshing the UI the application was disabled forever, I got to modify the file with db extension..

**Comment by alseambusher** [comment]
Thanks for reporting the issue. It has been fixed in https://github.com/alseambusher/crontab-ui/commit/970e461621e6906ce7259b9dfcacbff90dae858b
