### ISSUE TITLE
"Command too long" error when "Enable error logging" checked

### ISSUE THREAD

**Issue by timsayshey** [alseambusher/crontab-ui#150]
I can only save if I uncheck the `Enable error logging.` checkbox

Here is the error:

```
Error: Command failed: crontab /tmp/crontab
"/tmp/crontab":1: command too long
errors in crontab file, can't install.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'crontab /tmp/crontab'
}
```

Checkboxes:
- [x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues.

**Comment by peder1001** [comment]
I also have this issue
