### ISSUE TITLE
Crontui dead after adding cron job

### ISSUE THREAD

**Issue by No1zzz** [alseambusher/crontab-ui#20]
PORT=9000 crontab-ui
Crontab UI is running at http://localhost:8901
/usr/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:155
    throw new Error('Invalid characters, got value: ' + value)
    ^

Error: Invalid characters, got value: #
    at Function._parseField (/usr/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:155:11)
    at parse (/usr/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:639:36)
    at Function.parse (/usr/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/expression.js:650:10)
    at Function.parseExpression (/usr/lib/node_modules/crontab-ui/node_modules/cron-parser/lib/parser.js:39:25)
    at /usr/lib/node_modules/crontab-ui/crontab.js:50:32
    at newArguments.(anonymous function) (/usr/lib/node_modules/crontab-ui/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/usr/lib/node_modules/crontab-ui/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/usr/lib/node_modules/crontab-ui/node_modules/nedb/lib/cursor.js:126:19)
    at /usr/lib/node_modules/crontab-ui/node_modules/nedb/lib/cursor.js:193:12
    at /usr/lib/node_modules/crontab-ui/node_modules/nedb/lib/datastore.js:329:14

**Comment by alseambusher** [comment]
Can you share the job which you tried to run?

**Comment by alseambusher** [comment]
If you want to fix your crontab-ui instance, refer [this](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
