### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by GermanYoshi** [alseambusher/crontab-ui#204]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [ x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x ] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x ] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x ] Gone through existing open and closed issues. 

finkfw@FF-Auto-Linux:~/Crontab-UI$ crontab-ui
/usr/local/lib/node_modules/crontab-ui/crontab.js:27
var humanCronLocate = process.env.HUMANCRON ?? "en"
                                             ^
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/crontab-ui/app.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
finkfw@FF-Auto-Linux:~/Crontab-UI$

**Comment by GermanYoshi** [comment]
finkfw@FF-Auto-Linux:~/Crontab-UI$ crontab-ui
/usr/local/lib/node_modules/crontab-ui/crontab.js:27
var humanCronLocate = process.env.HUMANCRON ?? "en"
                                             ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/crontab-ui/app.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
finkfw@FF-Auto-Linux:~/Crontab-UI$

**Comment by aymen3009** [comment]
i had the same issue and it turns out that it was the node version that caused this.
so basically my user uses node v 19 but all the scripts that are running by the corn use v12.22.9

**Comment by thap2331** [comment]
Hey @aymen3009, I am not a node user. Could you share how did you make the user run v12.22.9? 

I am getting the above error as well.
My details: 
node --version is v12.22.9
npm --version is 8.5.1

**Comment by hd-vt** [comment]
i just did nano - c /usr/local/lib/node_modules/crontab-ui/crontab.js

on line 27: i removed  **?? "en"** and the file looks like this. 

![image](https://github.com/alseambusher/crontab-ui/assets/91519331/8c9e970c-b58f-4086-8f33-44215c070269)`

and the ui is working for me.
