### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by vendor-vandor** [alseambusher/crontab-ui#35]
:~# PORT=9000 crontab-ui
/usr/local/lib/node_modules/crontab-ui/app.js:191
crontab.autosave_crontab(()=>{});
                                         ^
SyntaxError: Unexpected token )
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/usr/local/lib/node_modules/crontab-ui/bin/crontab-ui.js:3:15)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)

:~# crontab-ui
/usr/local/lib/node_modules/crontab-ui/app.js:191
crontab.autosave_crontab(()=>{});
                                          ^
SyntaxError: Unexpected token )
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/usr/local/lib/node_modules/crontab-ui/bin/crontab-ui.js:3:15)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)

Checked rights, is this ok?
~# ls -ld $(npm root -g)/crontab-ui
drwxr-xr-x 10 nobody root 4096 Dec 22 01:15 /root/.npm-global/lib/node_modules/crontab-ui

nodejs --version v0.10.29
npm --version 1.4.21

Using debian jessie. Also same problem in centos7. There is something wrong in my setup, could someone tell how to fix this? I would be very happy to get over of this error.

**Comment by alseambusher** [comment]
Hi,

1. Your nodejs version is way too old. Don't use `apt-get` to install node. Get it from [here](https://nodejs.org/en/download/).
2. You should be fine if you are planning to run crontab-ui as root. Else you need to set right permissions. Please refer [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md).
