### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by pesseyjulien** [alseambusher/crontab-ui#47]
Hi,

I'm trying to use your tool but I'm getting the following error :

/usr/local/lib/node_modules/crontab-ui/crontab.js:79
				let stderr = "/tmp/" + tab._id + ".stderr";
				^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/crontab-ui/app.js:4:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

Any idea why ?

Thanks,
Julien

**Comment by pesseyjulien** [comment]
Never mind, I followed #274 and managed to fix my issue !
