### ISSUE TITLE
Issues installing crontab-ui - getting syntaxerror

### ISSUE THREAD

**Issue by charliejsford** [alseambusher/crontab-ui#77]
I have tried to install crontab-ui, which looks like it succeeded but when i run the cmd `crontab-ui` it return this:

```
root@vps80826:~# crontab-ui
/usr/local/lib/node_modules/crontab-ui/crontab.js:86
                                let stderr = path.join(cronPath, tab._id + ".stderr");
                                ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/crontab-ui/app.js:4:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

```

**Comment by alseambusher** [comment]
Install latest version of node and npm

**Comment by charliejsford** [comment]
just managed to work that out this morning before i saw this :)

is it possible to send HTTP requests?
